server:
  port: 8002

spring:
  main:
    allow-circular-references: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 955643515339-79mr8ck8p9t4itp5ebc11qv4jhuqmtf3.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

  data:
    mongodb:
      uri: mongodb://localhost:27017/auth

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  rabbitmq:
    host: localhost
    password: guest
    username: guest

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

trs:
  defaults:
    timezone: CST
    prefetchCount: 1
    concurrentConsumers: 1

rmq:
  userSend:
    queueName: userDetail
    exchangeName: user.exchange
    routingKey: user.userSend

